### ISSUE TITLE
Wave Background is not Snapping to Edge

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Landing-Page#5]
The purple wave is not snapping to edge in certain breakpoints, purple background color is also having trouble to snap sometimes

**Comment by rickkdev** [comment]
![snap](https://user-images.githubusercontent.com/28826387/113118772-11298d80-9210-11eb-9e6e-49e90e22a383.png)

**Comment by mktcode** [comment]
Using PNG instead of SVG solves the issue. The PNGs need to be of large size though, increasing the filesize by a factor of ~10 unfortunately.
